apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    namespace: score-server
    name: api
    labels:
      app: api
spec:
  replicas: 1
  template:
    metadata:
      matchLabels:
      labels:
        app: api
    spec:
      # restartPolicy: OnFailure
      initContainers:
      - name: waitdb
        image: jwilder/dockerize
        args: ['sh', '-c', 'dockerize -wait tcp://redis:6379 -timeout 100s', 'dockerize -wait tcp://db:5432 -timeout 100s']
      containers:
      - image: kyontan/netcon-score-server:api
        imagePullPolicy: Always
        name: api
        ports:
          - containerPort: 3000
        envFrom:
          - configMapRef:
              name: score-server-env
        args:
          - sh
          - -c
          - " if [ -f \"tmp/pids/server.pid\" ]; then rm tmp/pids/server.pid; fi\n
           bundle exec rails server -b 0.0.0.0;"
---
apiVersion: v1
kind: Service
metadata:
  namespace: score-server
  name: api
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
    - port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-production-bind-svc
spec:
  type: ExternalName
  externalName: api.production.svc.cluster.local
