apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ui
  name: ui
  namespace: score-server
spec:
  template:
    metadata:
      labels:
        app: ui
      namespace: score-server
    spec:
      containers:
        - image: kyontan/netcon-score-server:ui
          imagePullPolicy: Always
          name: ui
          ports:
            - name: ui
              containerPort: 3000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: score-server
  name: ui
spec:
  selector:
    app: ui
  type: ClusterIP
  ports:
    - port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ui-production-bind-svc
spec:
  type: ExternalName
  externalName: ui.production.svc.cluster.local
